### ISSUE TITLE
Inquiry crashed on arabic input

### ISSUE THREAD

**Issue by pinpong** [afollestad/inquiry#17]
```
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer E/SQLiteLog: (1) no such column: ١
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer D/AndroidRuntime: Shutting down VM
05-15 13:57:34.158 16635-16635/eu.pinpong.equalizer E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: eu.pinpong.equalizer, PID: 16635
                                                                      android.database.sqlite.SQLiteException: no such column: ١ (code 1): , while compiling: SELECT BAND_LEVEL_0, BAND_LEVEL_1, BAND_LEVEL_2, BAND_LEVEL_3, BAND_LEVEL_4, BASS_BOOST_ENABLED, BASS_BOOST_LEVEL, _id, LOUDNESS_ENHANCER_ENABLED, LOUDNESS_ENHANCER_LEVEL, PRESET_NAME, VIRTUALIZER_ENABLED, VIRTUALIZER_LEVEL FROM PRESETS WHERE PRESET_NAME = ? ORDER BY null LIMIT ١
                                                                          at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                          at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
                                                                          at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:498)
                                                                          at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                          at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                          at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
                                                                          at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:44)
                                                                          at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1316)
                                                                          at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1163)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1034)
                                                                          at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1202)
                                                                          at com.afollestad.inquiry.SQLiteHelper.query(SQLiteHelper.java:42)
                                                                          at com.afollestad.inquiry.Query.getInternal(Query.java:147)
                                                                          at com.afollestad.inquiry.Query.one(Query.java:169)
```

**Comment by afollestad** [comment]
I'm not sure if there's anything I can. It's most likely an SQLite compatibility issue with Unicode characters.

You'll have to stick with Latin letters.
