### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/inquiry#18]
``` gradle
FATAL EXCEPTION: main
                                                        Process: ro.allkids, PID: 714
                                                        java.lang.IllegalArgumentException: Cannot bind argument at index 3 because the index is out of range.  The statement has 0 parameters.
                                                            at android.database.sqlite.SQLiteProgram.bind(SQLiteProgram.java:212)
                                                            at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:166)
                                                            at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
                                                            at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
                                                            at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1318)
                                                            at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1165)
                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1036)
                                                            at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1204)
                                                            at com.afollestad.inquiry.SQLiteHelper.query(SQLiteHelper.java:42)
                                                            at com.afollestad.inquiry.Query.getInternal(Query.java:274)
                                                            at com.afollestad.inquiry.Query.all(Query.java:308)
                                                            at ro.allkids.managers.DataManager.getProductListbySearchTerm(DataManager.java:138)
                                                            at ro.allkids.fragments.SearchListFragment.refreshSearchResult(SearchListFragment.java:200)
                                                            at ro.allkids.fragments.SearchListFragment.updateSearchTerm(SearchListFragment.java:189)
                                                            at ro.allkids.fragments.SearchListFragment.access$000(SearchListFragment.java:42)
                                                            at ro.allkids.fragments.SearchListFragment$1.onQueryTextChange(SearchListFragment.java:171)
                                                            at android.support.v7.widget.SearchView.onTextChanged(SearchView.java:1228)
                                                            at android.support.v7.widget.SearchView$12.onTextChanged(SearchView.java:1758)
                                                            at android.widget.TextView.sendOnTextChanged(TextView.java:8182)
                                                            at android.widget.TextView.handleTextChanged(TextView.java:8244)
                                                            at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:10366)
                                                            at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1208)
                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:509)
                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
                                                            at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:844)
                                                            at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:198)
                                                            at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:183)
                                                            at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:345)
                                                            at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:91)
                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                            at android.os.Looper.loop(Looper.java:154)
                                                            at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

How can I handle to get for the following query good results ? 

``` java
Product[] result = Inquiry.get(context)
                .selectFrom(Product.TABLE, Product.class)
                .where("name LIKE '%?%'", searchTerm)
                .orWhere("description LIKE '%?%'", searchTerm)
                .orWhere("brand LIKE '%?%'", searchTerm)
                .all();
```

**Comment by afollestad** [comment]
Sorry for the late response. It turns out Android requires that you pass the wildcard percent signs in the arguments, like this:

```java
String searchTerm = "%Android%";

Product[] results = Inquiry.get(MainActivity.this)
    .select(Product.class)
    .where("name LIKE ?", searchTerm)
    .orWhere("description LIKE ?", searchTerm)
    .orWhere("brand LIKE ?", searchTerm)
    .all();
```

I've tested that, and it works.

---

Side note, you will definitely want to upgrade to Inquiry 4.1.2. I've fixed some bugs that will affect you, and I've added some big new features in the past new releases which are all detailed in the README on the front page.
