### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/inquiry#19]
Hello.

I am using Inqiury. I have a MainActivity which extend the FragmentActivity. 

I am setting up at first run a Fragment with a ListView, which is initialized with data from database, But I don't know why, the  adapter initialization is called before the onResume Method, in the Main Activity. 
I am getting the following error:

```Gradle
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                           Caused by: java.lang.IllegalStateException: No persisted instance found for ro.allkids.activities.MainActivity, or it's been garbage collected.
                                                              at com.afollestad.inquiry.Inquiry.get(Inquiry.java:246)
                                                              at com.afollestad.inquiry.Inquiry.get(Inquiry.java:239)
```

How can I handle this error?

Many thanks, 
Andrew

**Comment by afollestad** [comment]
Well, it'd help if you included some actual code. By the way, I updated your comment to use multi-line syntax highlighting ;-)

If you instantiate an instance with a name, you can retrieve it by name rather than context; you can see how that's done here: https://github.com/afollestad/inquiry#instances

Once you initialize it with a name, you can just do this:

```java
Inquiry instance = Inquiry.get("instance-name");
```

---

I'd recommend initializing and keeping track of the instance from within the Fragment if you're using a Fragment. You can use a separate instance in the Fragment and a separate instance in the Activity, also.

**Comment by afollestad** [comment]
But I am using this library in multiple production apps with no problems. So there are no bugs here.
