### ISSUE TITLE
Inserting Data

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/inquiry#21]
Hello. 
Thank you for this library.
I am getting the following error all the time i want to use the library:

```gradle
11-08 22:33:20.206 20115-22119/? E/AndroidRuntime: FATAL EXCEPTION: Thread-25
                                                   Process: ro.allkids, PID: 20115
                                                   java.lang.NullPointerException: Attempt to invoke virtual method 'long com.afollestad.inquiry.SQLiteHelper.insert(java.lang.String, android.content.ContentValues)' on a null object reference
                                                       at com.afollestad.inquiry.Query.run(Query.java:447)
                                                       at com.afollestad.inquiry.Query$2.run(Query.java:566)
                                                       at java.lang.Thread.run(Thread.java:761)
```

I am using the following code in a loop, and after the 4th / 5th loop, I get the error.

```java
Inquiry.get(this)
                    .insert(Product.class)
                    .values(productList)
                    .run(changed -> {
                    });
```

Thank you.

**Comment by afollestad** [comment]
I've never experienced that issue.

Did you initialize an Inquiry instance correctly?

**Comment by afollestad** [comment]
Yeah, that's the problem. You didn't initialize an Inquiry instance with a database name.

https://github.com/afollestad/inquiry#instances
