### ISSUE TITLE
MySqlHelper is null

### ISSUE THREAD

**Issue by ferenczAndras** [afollestad/inquiry#22]
Hello,
I changed the code, to use the name Instances.

If I debug my code, everything works fine, if not I am getting the following error:

```gradle
FATAL EXCEPTION: Thread-11
                                                          Process: ro.allkids, PID: 5285
                                                          java.lang.IllegalStateException: Database helper was null.
                                                              at com.afollestad.inquiry.Query.getInternal(Query.java:326)
                                                              at com.afollestad.inquiry.Query.all(Query.java:401)
                                                              at com.afollestad.inquiry.Query$1.run(Query.java:408)
                                                              at java.lang.Thread.run(Thread.java:761)
```

This is the code segment what I am using:

```java
Inquiry inquiry = Inquiry.get(App.DATA_BASE_INSTANCE_NAME);
            inquiry.select(Product.class)
                    .where("categoryid = ? ", category.categoryId)
                    .orWhere("categoryid = ? ", category.getFirstSubCategory())
                    .sort(orderBy)
                    .sortByAsc("id")
                    .all(result -> {
                        if (result != null) {
                            adapter.setItems(new ArrayList<>(Arrays.asList(result)));
                            adapter.notifyDataSetChanged();
                        } else {
                            List<Product> productList = new ArrayList<>();
                            adapter.setItems(productList);
                            adapter.notifyDataSetChanged();
                        }
                        categoryDataLoadedListener.onCategoryDataWasLoaded();

                    });
```

Thank you :)

**Comment by afollestad** [comment]
You need to initialize Inquiry instances with a database name.

https://github.com/afollestad/inquiry#instances

**Comment by ferenczAndras** [comment]
I am initializing the Instances like this :
```
      Inquiry.newInstance(MainActivity.this, AllKidsApp.DATA_BASE)
                .instanceName(AllKidsApp.DATA_BASE_INSTANCE_NAME)
                .build();
```

Where: 

```
 public final static String DATA_BASE = "all_kids_database_first";

    public final static String DATA_BASE_INSTANCE_NAME = "mainInstance";
```

**Comment by afollestad** [comment]
Weird. There must be something else wrong in your code, I use this library in multiple production apps and haven't had any issues like this.

**Comment by afollestad** [comment]
Oh, it's because you gave the instance a name. You need to use `Inquiry.get("instance-name");`

**Comment by ferenczAndras** [comment]
I did everything what you told me. The weird part of it is, that if i debug the code line by line, at the and everything works fine. If not, I am getting the same error again and again.

**Comment by afollestad** [comment]
That sounds like it could me a threading issue, you may be accessing the DB before it's initialized or something.

**Comment by afollestad** [comment]
Or after the instance is destroyed.
