### ISSUE TITLE
Can't downgrade database version

### ISSUE THREAD

**Issue by pinpong** [afollestad/inquiry#24]
Fatal Exception: android.database.sqlite.SQLiteException: Can't downgrade database from version 6 to 1
       at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:376)
       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:270)
       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:175)
       at com.afollestad.inquiry.SQLiteHelper.createTableIfNecessary(SQLiteHelper.java:23)
       at com.afollestad.inquiry.Query.(Query.java:79)
       at com.afollestad.inquiry.Inquiry.select(Inquiry.java:260)

**Comment by afollestad** [comment]
That's unrelated to this library.

**Comment by pinpong** [comment]
Whats the issue?

**Comment by afollestad** [comment]
The package is `android.database.sqlite`, that's in the Android framework. The Android framework doesn't let you downgrade databases, for the same reason you can't publish an old version of an app to Google Play.

**Comment by pinpong** [comment]
I got this issue after i updated inquiry:3.2.1 to inquiry:4.1.2.

**Comment by afollestad** [comment]
It would've been an issue in any other version, it's not in my control and it doesn't make sense to downgrade and upgraded DB.

**Comment by yiki-ecnavi** [comment]
Does the bug fixed?
