### ISSUE TITLE
NullPointerException getIdDelegate() & getBuilderClass()

### ISSUE THREAD

**Issue by ritdaw** [afollestad/inquiry#27]
- Library version: 5.0
 - Device OS version: 4.4.2
 - Device Manufacturer: softwinner
 - Device Name: unknown

We are getting some NPEs through crashlytics for a specific group of test devices (all the same devices). Both the below NPEs seem to relate to 2 cache methods (getBuilderClassCache() & getIdProxyCache()). 
As a side note, the same devices are weirdly reporting an error relating to the database name being null, we only call the newinstance() once. Is there a chance that the instance has been destroyed and this is the cause of all of the errors?

```
Inquiry.newInstance(this, INQUIRY_DB_NAME)
		.instanceName(INQUIRY_INSTANCE)
		.databaseVersion(INQUIRY_DB_VERSION)
		.build();
```

Any thoughts?

```java
Fatal Exception: java.lang.NullPointerException
       at com.afollestad.inquiry.Inquiry.getIdDelegate(Inquiry.java:64)
       at com.afollestad.inquiry.Query.run(Query.java:444)
       at com.afollestad.inquiry.Query$2.run(Query.java:607)
       at java.lang.Thread.run(Thread.java:841)
```

```
Fatal Exception: java.lang.NullPointerException
       at com.afollestad.inquiry.Inquiry.getBuilderClass(Inquiry.java:88)
       at com.afollestad.inquiry.Query.run(Query.java:439)
       at com.afollestad.inquiry.Query$2.run(Query.java:607)
       at java.lang.Thread.run(Thread.java:841)
```

```
Fatal Exception: java.lang.IllegalStateException: You must initialize your Inquiry instance with a non-null database name.
       at com.afollestad.inquiry.Inquiry._getDatabase(Inquiry.java:50)
       at com.afollestad.inquiry.Query.run(Query.java:468)
       at com.afollestad.inquiry.Query$2.run(Query.java:607)
       at java.lang.Thread.run(Thread.java:841)
```

**Comment by afollestad** [comment]
Hmm, yeah that looks like it's due to the instance being destroyed, so the caches don't exist

**Comment by ritdaw** [comment]
I had assumed that was the case but thought I'd flag it up anyway.

**Comment by ritdaw** [comment]
Should these exceptions be catchable by a try catch? Haven't been able to track down the cause of this issue.

**Comment by ritdaw** [comment]
Any thoughts? We were using 3.2.1 with no issues but would rather not go back due to all the nice new features.

**Comment by afollestad** [comment]
They are catchable, you catch `NullPointerException` anywhere you execute a `Query` (`.run()`).

**Comment by ritdaw** [comment]
Is a bit strange as they don't appear to getting caught, there was one call which wasn't surrounded in a try catch but has since been added. Crashlytics is still reporting NPEs, unfortunately I've found it impossible to reproduce on any of my devices.

**Comment by ritdaw** [comment]
I think the GC is destroying the instance as the device in question doesn't have a lot of RAM.

**Comment by ritdaw** [comment]
FYI we've started seeing this on more devices during a staged rollout
```
Fatal Exception: java.lang.IllegalStateException: You must initialize your Inquiry instance with a non-null database name.
```

**Comment by ritdaw** [comment]
Any thoughts on this one?
