### ISSUE TITLE
setter method of boolean excpected to be isFieldName(boolean b)

### ISSUE THREAD

**Issue by msegmx** [afollestad/inquiry#30]
I have this code in my Pojo class :

```
	@Column
	public boolean isNsfw() {
		return nsfw;
	}

	public void setNsfw(boolean nsfw) {
		this.nsfw = nsfw;
	}
```
I get following exception :
```

java.lang.IllegalStateException: Column getter method isNsfw does not have an equivalent setter method with signature void isNsfw(boolean)
                                                                                    at com.afollestad.inquiry.FieldDelegate.<init>(FieldDelegate.java:98)
                                                                                    at com.afollestad.inquiry.Converter.classFieldDelegates(Converter.java:449)
                                                                                    at com.afollestad.inquiry.Converter.classFieldDelegates(Converter.java:415)
                                                                                    at com.afollestad.inquiry.Query.run(Query.java:440)
```

Shouldn't the setter method of booleans also start with "set" ?

**Comment by HeinrichReimer** [comment]
I guess inquiry is not recognizing `is...()` methods as getter methods but instead assumes that the field would have a name `is...` and thus thinks that the setters/getters would both be named `isNsfw()`.

You can fix this temporarily by replacing `isNsfw()` with `getNsfw()`.

**Comment by afollestad** [comment]
Generally boolean getters and setters both begin with `is`.

**Comment by heinrichreimer** [comment]
Depends on personal preference... I use `is` for getters and `set` for setters... Anyway, Inquiry should support both types

**Comment by afollestad** [comment]
Well, the way it is now is a standard and I don't intent to change it.

If you use `set` for a setter, you're supposed to use `get` for the opposite. That's the Java Bean pattern.

**Comment by heinrichreimer** [comment]
Right, it is **a** standard. IntelliJ for example uses `is` for getters and `set` for setters.

**Comment by afollestad** [comment]
The standard using get and set together, or not at all.

**Comment by msegmx** [comment]
First of all, I simply added a isNsfw method (coding a Reddit widget). No big deal.
Your library/idea/approach is perfect, couldn't find anything close to it on androidarsenal.com.

But the javaBeans specification says that you may add a "is.." getter to boolean fields.

(from [Oracle](http://www.oracle.com/technetwork/articles/javaee/spec-136004.html))
> 8.3.2 Boolean properties
> In addition, for boolean properties, we allow a getter method to match the pattern:
> public boolean is<PropertyName>();
> This “is<PropertyName>” method may be provided instead of a “get<PropertyName>” method,
> or it may be provided in addition to a “get<PropertyName>” method.
> In either case, if the “is<PropertyName>” method is present for a boolean property then we will
> use the “is<PropertyName>” method to read the property value.
> An example boolean property might be:
> public boolean isMarsupial();
> public void setMarsupial(boolean m);

It doesn't say anything about the setters though, which implies that there's no alternative to "set..".
