### ISSUE TITLE
@Column int[]

### ISSUE THREAD

**Issue by nwhessel** [afollestad/inquiry#8]
```java
public class Course {

	@Column(name = "_id", primaryKey = true, notNull = true, autoIncrement = true)
	private long id;
	@Column
	private String name;
	@Column
	private int[] par;
	
	public Course(String name, int[] par) {
		this.name = name;
		this.par = par;
	}

	//...
}
```
```java
public class MainActivity extends TabActivity {

    //...

    @Override
    public void onResume() {
        super.onResume();
        Inquiry.init(this, "myDatabase", 1);

        Inquiry.get().dropTable("courses");

        Course ribMountain = new Course("Rib Mountain", new int[] {3,3,4,4,4,3,3,4,4});
        Course pineValley = new Course("Pine Valley", new int[] {5,4,4,4,4,3,4,4,3, 4,5,4,3,5,4,4,3,4});
        Course craneMeadows = new Course("Crane Meadows", new int[] {4,4,3,4,4,5,5,3,4});
        Course trappRiver = new Course("Trapp River", new int[] {4,4,4,4,5,4,3,5,3, 4,4,3,5,4,4,4,4,4});

        long insertedCourses = Inquiry.get()
                .insertInto("courses", Course.class)
                .values(ribMountain, pineValley, craneMeadows, trappRiver)
                .run();
    }

    @Override
    public void onPause() {
        super.onPause();
        Inquiry.deinit();
    }
}
```

```java
public class CoursesFragment extends Fragment {

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View rootView = inflater.inflate(R.layout.fragment_courses, container, false);

        Course[] courses = Inquiry.get()
                .selectFrom("courses", Course.class)
                .all();

        return rootView;
    }
}
```

```Gradle
12-12 12:38:11.600: E/AndroidRuntime(20680): java.lang.RuntimeException: Failed to instantiate com.hesselapplications.caddie.Golf.Course: wrong number of arguments; expected 2, got 0
12-12 12:38:11.600: E/AndroidRuntime(20680): 	at com.afollestad.inquiry.Utils.newInstance(Utils.java:22)
12-12 12:38:11.600: E/AndroidRuntime(20680): 	at com.afollestad.inquiry.ClassRowConverter.cursorToCls(ClassRowConverter.java:211)
12-12 12:38:11.600: E/AndroidRuntime(20680): 	at com.afollestad.inquiry.Query.getInternal(Query.java:113)
12-12 12:38:11.600: E/AndroidRuntime(20680): 	at com.afollestad.inquiry.Query.all(Query.java:135)
12-12 12:38:11.600: E/AndroidRuntime(20680): 	at com.hesselapplications.caddie.Fragments.CoursesFragment.onCreateView(CoursesFragment.java:28)
```

**Comment by afollestad** [comment]
Updated your code for proper formatting and syntax highlighting. 

As mentioned in the README, the class causing trouble needs a default constructor with no parameters.

**Comment by nwhessel** [comment]
Ah yes, thank you
